# Generated by Django 4.2.1 on 2023-07-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="imagem",
            field=models.ImageField(null=True, upload_to="task"),
        ),
    ]
